### resource not found
GET http://localhost:3000/api/null

### Récupération des tous les auteurs
GET http://localhost:3000/api/authors

### Récupération d'un auteur
GET http://localhost:3000/api/authors/4

### Ajout d'auteur
POST http://localhost:3000/api/authors
Content-Type: application/json

{
    "firstname": "Klaus-Jürgen",
    "lastname": "Wrede"
}

### Update d'auteur
PATCH http://localhost:3000/api/authors/4
Content-Type: application/json

{
    "firstname": "Klaus"
}


### delete d'auteur
DELETE http://localhost:3000/api/authors/4

_____________________________________________________
_____________________________________________________


### Récupération des tous les éditeurs
GET http://localhost:3000/api/publishers

### Récupération d'un éditeur
GET http://localhost:3000/api/publishers/1

### Ajout d'un éditeur
POST http://localhost:3000/api/publishers
Content-Type: application/json

{
    "name": "Zman Games"
}

### Update du éditeur
PATCH http://localhost:3000/api/publishers/1
Content-Type: application/json

{
    "name": "kosmoss"
}


### delete d'un éditeur
DELETE http://localhost:3000/api/publishers/3


_____________________________________________________
_____________________________________________________


### Récupération de tous les jeux
GET http://localhost:3000/api/games

### Récupération d'un jeu
GET http://localhost:3000/api/games/8

### Ajout d'un jeu
POST http://localhost:3000/api/games
Content-Type: application/json

{
    "title": "Carcassonne",
    "locale": "fr_FR",
    "year": 2001,
    "age_min": 6,
    "duration": 45,
    "player_num_min": 2,
    "player_num_max": 5,
    "cover": null,
    "publisher_id": 4,
    "author_id": [5],
    "theme_id": [2],
    "mechanics_id": [1, 6]
}

### Update d'un jeu
PATCH http://localhost:3000/api/games/11
Content-Type: application/json

{
    "title": "Carcassonnes",
    "locale": "en_EN",
    "year": "2002",
    "age_min": 10,
    "duration": 60,
    "player_num_min": 1,
    "player_num_max": 6,
    "cover": null,
    "publisher_id": 1,
    "author_id": [3],
    "theme_id": [1],
    "mechanics_id": [3, 4]
}

### delete d'un jeu
DELETE http://localhost:3000/api/games/11


_____________________________________________________
_____________________________________________________

### Récupération de toutes les mécaniques
GET http://localhost:3000/api/mechanics

### Récupération dune mécanique
GET http://localhost:3000/api/mechanics/4

### Ajout d'une mécanique
POST http://localhost:3000/api/mechanics
Content-Type: application/json

{
    "label": "test"
}

### Update d'une mechanics
PATCH http://localhost:3000/api/mechanics/7
Content-Type: application/json

{
    "label": "tests"
}

### delete d'une mécanique
DELETE http://localhost:3000/api/mechanics/7

